# Generated by Django 5.1.4 on 2024-12-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.BinaryField()),
                ('valoracion', models.IntegerField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('idenvio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('direccion_entrega', models.CharField(max_length=120)),
                ('fono_contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'envios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('idestado', models.BooleanField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.TextField()),
            ],
            options={
                'db_table': 'galeria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idmetodopago', models.BooleanField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idrepartidor', models.AutoField(primary_key=True, serialize=False)),
                ('rut_rep', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_pat', models.CharField(max_length=60)),
                ('apellido_mat', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=120)),
                ('fono', models.IntegerField()),
            ],
            options={
                'db_table': 'repartidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('iduser_perfil', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'user_perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut', models.AutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_pat', models.CharField(max_length=50)),
                ('apellido_mat', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=120)),
                ('contrasena', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('capacidad_kilos', models.IntegerField()),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('idusuario', models.FloatField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idproducto', models.OneToOneField(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.productos')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
    ]
