# Generated by Django 5.1.4 on 2024-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comuna_productos_estadoenvio_metodopago_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.TextField(),
        ),
    ]
