# Generated by Django 5.1.4 on 2024-12-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_productos_descripcion_alter_productos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='idmetodopago',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
