# Generated by Django 5.1.4 on 2024-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_estadoenvio_idestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoenvio',
            name='idestado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
